SELECT dp."LINGUAGEM CIDADÃ", SUM(ft."VALOR TRANSFERIDO") AS "TOTAL TRANSFERIDO"
FROM Fato_Transferencias ft
JOIN Dim_Programa dp ON ft.ID_PROGRAMA = dp.ID_PROGRAMA
WHERE dp."LINGUAGEM CIDADÃ" IS NOT NULL AND dp."LINGUAGEM CIDADÃ" != 'NÃO INFORMADO'
GROUP BY dp."LINGUAGEM CIDADÃ"
ORDER BY "Total transferido" DESC
LIMIT 10