SELECT dt."ANO / MÊS", SUM(ft."VALOR TRANSFERIDO") AS total_recebido_UFPE
FROM Fato_Transferencias ft
JOIN Dim_Favorecido df ON ft.ID_FAVORECIDO = df.ID_FAVORECIDO
JOIN Dim_Tempo dt ON ft.ID_TEMPO = dt.ID_TEMPO
WHERE df."NOME FAVORECIDO" LIKE '%UNIVERSIDADE FEDERAL DE PERNAMBUCO%'
GROUP BY dt."ANO / MÊS"
ORDER BY dt."ANO / MÊS" ASC